heat_template_version: 2016-04-08
parameters:
  key:
    type: string
    description: instance key
  flavor:
    type: string
    description: Instance type for the instance to be created
    default: m1.tiny
  image:
    type: string
    default: cirros
    description: ID or name of the image to use for the instance
  public_net_id:
    type: string
    description: Public network id
    default: provider
resources:
  instance1:
    type: OS::Nova::Server
    properties:
      name: tp1-ej1_vm1
      image: xenial-server
      key_name: { get_param: key }
      flavor: m1.peque
      networks:
        - port: { get_resource: port1 }
        - port: { get_resource: port7 }
  instance2:
    type: OS::Nova::Server
    properties:
      name: tp1-ej1_vm2
      image: cirros
      key_name: { get_param: key }
      flavor: m1.tiny
      networks:
        - port: { get_resource: port2 }
        - port: { get_resource: port3 }
        - port: { get_resource: port8 }
        - port: { get_resource: port9 }
  instance3:
    type: OS::Nova::Server
    properties:
      name: tp1-ej1_vm3
      image: cirros
      key_name: { get_param: key }
      flavor: m1.tiny
      networks:
        - port: { get_resource: port4 }
        - port: { get_resource: port5 }
        - port: { get_resource: port10 }
        - port: { get_resource: port11 }
  instance4:
    type: OS::Nova::Server
    properties:
      name: tp1-ej1_vm4
      image: xenial-server
      key_name: { get_param: key }
      flavor: m1.peque
      networks:
        - port: { get_resource: port6 }
        - port: { get_resource: port12 }
  port1:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p1
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port2:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p2
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port3:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p3
      network_id: { get_resource: net3 }
      fixed_ips:
        - subnet_id: { get_resource: subnet3 }
  port4:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p4
      network_id: { get_resource: net3 }
      fixed_ips:
        - subnet_id: { get_resource: subnet3 }
  port5:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p5
      network_id: { get_resource: net2 }
      fixed_ips:
        - subnet_id: { get_resource: subnet2 }
  port6:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p6
      network_id: { get_resource: net2 }
      fixed_ips:
        - subnet_id: { get_resource: subnet2 }
  net1:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet1:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net1 }
      cidr: 10.10.10.0/24
  net2:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet2:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net2 }
      cidr: 10.10.11.0/24
  net3:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet3:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net3 }
      cidr: 10.10.12.0/24
  port7:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p7
      network_id: { get_resource: net4 }
      fixed_ips:
        - subnet_id: { get_resource: subnet4 }
  port8:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p8
      network_id: { get_resource: net4 }
      fixed_ips:
        - subnet_id: { get_resource: subnet4 }
  port9:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p9
      network_id: { get_resource: net5 }
      fixed_ips:
        - subnet_id: { get_resource: subnet5 }
  port10:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p10
      network_id: { get_resource: net5 }
      fixed_ips:
        - subnet_id: { get_resource: subnet5 }
  port11:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p11
      network_id: { get_resource: net6 }
      fixed_ips:
        - subnet_id: { get_resource: subnet6 }
  port12:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p11
      network_id: { get_resource: net6 }
      fixed_ips:
        - subnet_id: { get_resource: subnet6 }
  net4:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet4:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net4 }
      cidr: 172.16.0.0/24
      gateway_ip: ''
  net5:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet5:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net5 }
      cidr: 172.16.1.0/24
      gateway_ip: ''
  net6:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet6:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net6 }
      cidr: 172.16.2.0/24
      gateway_ip: ''
  floating_ip1:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port1 }
  floating_ip2:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port2 }
  floating_ip3:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port4 }
  floating_ip4:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port6 }
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net_id }
  router_interface1:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet1 }
  router_interface2:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet2 } 
  router_interface3:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet3 }  
outputs:
  instance_ip1:
    description: Direccion IPv4 de Instancia1.
    value: { get_attr: [ floating_ip1, floating_ip_address ] }
  instance_ip2:
    description: Direccion IPv4 de Instancia2.
    value: { get_attr: [ floating_ip2, floating_ip_address ] }
  instance_ip3:
    description: Direccion IPv4 de Instancia3.
    value: { get_attr: [ floating_ip3, floating_ip_address ] }
  instance_ip4:
    description: Direccion IPv4 de Instancia4.
    value: { get_attr: [ floating_ip4, floating_ip_address ] }

