heat_template_version: 2016-04-08
parameters:
  key:
    type: string
    description: instance key
  flavor:
    type: string
    description: Instance type for the instance to be created
    default: m1.tiny
  image:
    type: string
    default: cirros
    description: ID or name of the image to use for the instance
  public_net_id:
    type: string
    description: Public network id
    default: provider
  router:
    type: string
    description: Router
    default: router
resources:
  net1:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet1:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net1 }
      cidr: 10.10.10.0/24
  floating_ip1:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port1 }
  floating_ip2:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port2 }
  floating_ip3:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port3 }
  floating_ip4:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port4 }
  floating_ip5:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port5 }
  floating_ip6:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port6 }
  floating_ip7:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port7 }
  floating_ip8:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port8 }
  floating_ip9:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: port9 }
  router_interface1:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_param: router }
      subnet: { get_resource: subnet1 }
  port1:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p1
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port2:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p2
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port3:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p3
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port4:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p4
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port5:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p5
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port6:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p6
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  
  port7:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p7
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port8:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p8
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  port9:
    type: OS::Neutron::Port
    properties:
      name: tp1-ej1_p9
      network_id: { get_resource: net1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }
  instance1:
    type: OS::Nova::Server
    properties:
      name: tp5_vm1
      image: xenial-server
      key_name: { get_param: key }
      flavor: m1.peque
      networks:
        - port: { get_resource: port1 }
        - port: { get_resource: port10 }
  instance2:
    type: OS::Nova::Server
    properties:
      name: tp5_vm2
      image: xenial-server
      key_name: { get_param: key }
      flavor: m1.peque
      networks:
        - port: { get_resource: port2 }
        - port: { get_resource: port11 }
  instance3:
    type: OS::Nova::Server
    properties:
      name: tp5_vm3
      image: xenial-server
      key_name: { get_param: key }
      flavor: m1.peque
      networks:
        - port: { get_resource: port3 }
        - port: { get_resource: port12 }
  instance4:
    type: OS::Nova::Server
    properties:
      name: tp5_vm4
      image: cirros
      flavor: m1.tiny
      networks:
        - port: { get_resource: port4 }
        - port: { get_resource: port13 }
        - port: { get_resource: port14 }
  instance5:
    type: OS::Nova::Server
    properties:
      name: tp5_vm5
      image: cirros
      flavor: m1.tiny
      networks:
        - port: { get_resource: port5 }
        - port: { get_resource: port15 }
        - port: { get_resource: port16 }
  instance6:
    type: OS::Nova::Server
    properties:
      name: tp5_vm6
      image: cirros
      flavor: m1.tiny
      networks:
        - port: { get_resource: port6 }
        - port: { get_resource: port17 }
        - port: { get_resource: port18 }
  instance7:
    type: OS::Nova::Server
    properties:
      name: tp5_vm7
      image: cirros
      flavor: m1.tiny
      networks:
        - port: { get_resource: port7 }
        - port: { get_resource: port19 }
        - port: { get_resource: port20 }
  instance8:
    type: OS::Nova::Server
    properties:
      name: tp5_vm8
      image: cirros
      flavor: m1.tiny
      networks:
        - port: { get_resource: port8 }
        - port: { get_resource: port21 }
        - port: { get_resource: port22 }
  instance9:
    type: OS::Nova::Server
    properties:
      name: tp5_vm9
      image: cirros
      flavor: m1.tiny
      networks:
        - port: { get_resource: port9 }
        - port: { get_resource: port23 }
        - port: { get_resource: port24 }
  net2:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet2:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net2 }
      cidr: 172.16.0.0/24
      gateway_ip: ''
  net3:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet3:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net3 }
      cidr: 172.16.1.0/24
      gateway_ip: ''
  net4:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet4:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net4 }
      cidr: 172.16.2.0/24
      gateway_ip: ''
  net5:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet5:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net5 }
      cidr: 172.16.3.0/24
      gateway_ip: ''
  net6:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet6:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net6 }
      cidr: 172.16.4.0/24
      gateway_ip: ''
  net7:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet7:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net7 }
      cidr: 172.16.5.0/24
      gateway_ip: ''
  net8:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  subnet8:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net8 }
      cidr: 172.16.6.0/24
      gateway_ip: ''
  port10:
    type: OS::Neutron::Port
    properties:
      name: tp5_p10
      network_id: { get_resource: net2 }
      fixed_ips:
        - subnet_id: { get_resource: subnet2 }
  port11:
    type: OS::Neutron::Port
    properties:
      name: tp5_p11
      network_id: { get_resource: net2 }
      fixed_ips:
        - subnet_id: { get_resource: subnet2 }
  port12:
    type: OS::Neutron::Port
    properties:
      name: tp5_p12
      network_id: { get_resource: net3 }
      fixed_ips:
        - subnet_id: { get_resource: subnet3 }
  port13:
    type: OS::Neutron::Port
    properties:
      name: tp5_p13
      network_id: { get_resource: net3 }
      fixed_ips:
        - subnet_id: { get_resource: subnet3 }
  port14:
    type: OS::Neutron::Port
    properties:
      name: tp5_p14
      network_id: { get_resource: net4 }
      fixed_ips:
        - subnet_id: { get_resource: subnet4 }
  port15:
    type: OS::Neutron::Port
    properties:
      name: tp5_p15
      network_id: { get_resource: net4 }
      fixed_ips:
        - subnet_id: { get_resource: subnet4 }
  port16:
    type: OS::Neutron::Port
    properties:
      name: tp5_p16
      network_id: { get_resource: net4 }
      fixed_ips:
        - subnet_id: { get_resource: subnet4 }
  port17:
    type: OS::Neutron::Port
    properties:
      name: tp5_p17
      network_id: { get_resource: net5 }
      fixed_ips:
        - subnet_id: { get_resource: subnet5 }
  port18:
    type: OS::Neutron::Port
    properties:
      name: tp5_p18
      network_id: { get_resource: net5 }
      fixed_ips:
        - subnet_id: { get_resource: subnet5 }
  port19:
    type: OS::Neutron::Port
    properties:
      name: tp5_p19
      network_id: { get_resource: net6 }
      fixed_ips:
        - subnet_id: { get_resource: subnet6 }
  port20:
    type: OS::Neutron::Port
    properties:
      name: tp5_p20
      network_id: { get_resource: net6 }
      fixed_ips:
        - subnet_id: { get_resource: subnet6 }
  port21:
    type: OS::Neutron::Port
    properties:
      name: tp5_p21
      network_id: { get_resource: net7 }
      fixed_ips:
        - subnet_id: { get_resource: subnet7 }
  port22:
    type: OS::Neutron::Port
    properties:
      name: tp5_p22
      network_id: { get_resource: net7 }
      fixed_ips:
        - subnet_id: { get_resource: subnet7 }
  port23:
    type: OS::Neutron::Port
    properties:
      name: tp5_p23
      network_id: { get_resource: net8 }
      fixed_ips:
        - subnet_id: { get_resource: subnet8 }
  port24:
    type: OS::Neutron::Port
    properties:
      name: tp5_p24
      network_id: { get_resource: net8 }
      fixed_ips:
        - subnet_id: { get_resource: subnet8 }
outputs:
